services:
  # Infrastructure Services
  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: yardly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - microservices-network

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'ruok' | nc localhost 2181"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-network

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    container_name: kafka-broker
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - microservices-network

  api-gateway:
    build: 
      context: .
      dockerfile: ./api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - USER_SERVICE_URL=http://user-service:3001
      - AUTH_SERVICE_URL=http://auth-service:3002
      - AUTHNZ_SERVICE_URL=http://authnz-service:3003
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    networks:
      - microservices-network
    depends_on:
      - auth-service
      - authnz-service
      - user-service

  # Microservices
  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    container_name: user-service
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/yardly
      - KAFKA_BROKERS=kafka-broker:9092
      - INTERNAL_SERVICE_TOKEN=super-secret-token
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=yardly
      - PORT=3001
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - microservices-network

  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
    container_name: auth-service
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres-db:5432/yardly
      - REDIS_URL=redis://redis-cache:6379
      - USER_SERVICE_URL=http://user-service:3001/internal
      - INTERNAL_SERVICE_TOKEN=super-secret-token
      - JWT_ACCESS_SECRET=supersecretaccesstoken
      - JWT_REFRESH_SECRET=supersecretrefreshtoken
      - JWT_RESET_SECRET=supersecretresettoken
      - JWT_SECRET=your_super_secret_jwt_key_here_make_it_long_and_random
      - JWT_EXPIRES_IN=24h
      - POSTGRES_HOST=postgres-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=yardly
      - PORT=3002
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - microservices-network

  authnz-service:
    build: 
      context: .
      dockerfile: ./authnz-service/Dockerfile
    container_name: authnz-service
    environment:
      - NODE_ENV=development
      - PORT=3003
    volumes:
      - ./authnz-service:/app
      - /app/node_modules
    networks:
      - microservices-network

  email-service:
    build:
      context: .
      dockerfile: ./email-service/Dockerfile
    container_name: email-service
    environment:
      - PORT=3004
      - REDIS_URL=redis://redis-cache:6379
      - KAFKA_BROKERS=kafka-broker:9092
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - EMAIL_USER=
      - EMAIL_PASS=
      - INTERNAL_SERVICE_TOKEN=super-secret-token
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - microservices-network

volumes:
  postgres_data:
  kafka_data:

networks:
  microservices-network:
    driver: bridge